### ISSUE TITLE
NullReference when using "GetTypeOfValue"

### ISSUE THREAD

**Issue by pingvinen** [rapidcore/rapidcore#93]
I was doing a test with the following setup
```csharp
changes.Changes.Add(new StateChange { Breadcrumb = "One", OldValue = "neo", NewValue = "smith" });
changes.Changes.Add(new StateChange { Breadcrumb = "Two", OldValue = "owt", NewValue = null });
```

As part of my code, a call to get the value of the `NewValue` property is made - which resulted in...

```
System.NullReferenceException : Object reference not set to an instance of an object.
   at RapidCore.Reflection.MemberInfoGetTypeOfValueExtensions.GetTypeOfValue(MemberInfo memberInfo)
   at RapidCore.Diffing.StateChange.GetDefaultValue()
```

**Comment by pingvinen** [comment]
False alarm... because I was testing something related to the `NewValue = null` handling, I hit a null reference in `StateChange.GetDefaultValue()`, which is using the `StateChange.MemberInfo` value - which I had not set.
